# Generated by Django 5.0.3 on 2024-03-14 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
